# Generated by Django 5.2.2 on 2025-06-13 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=250)),
                ('phone_number', models.CharField(max_length=20)),
                ('post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('town_or_city', models.CharField(max_length=100)),
                ('street_address_1', models.CharField(max_length=200)),
                ('street_address_2', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(max_length=70)),
                ('gym_location', models.CharField()),
                ('membership_type', models.CharField()),
                ('is_member_active', models.BooleanField(default=False)),
                ('membership_start', models.DateTimeField()),
                ('next_payment_date', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
