# Generated by Django 5.2.2 on 2025-06-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='gym_location',
            field=models.CharField(choices=[('hounslow', 'Hounslow')]),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('regular', 'Regular')]),
        ),
        migrations.AlterField(
            model_name='membership',
            name='next_payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
