# Generated by Django 5.2.2 on 2025-06-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_membership_gym_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='county',
            field=models.CharField(default='london', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
