# Generated by Django 5.2.2 on 2025-06-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_membership_county_alter_membership_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='next_payment_date',
            new_name='membership_end_date',
        ),
    ]
