# Generated by Django 5.2.2 on 2025-06-17 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_rename_membership_start_membership__end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='_end',
            new_name='membership_start_end',
        ),
    ]
