# Generated by Django 5.2.2 on 2025-06-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_rename__end_membership_membership_start_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='membership_start_end',
            new_name='membership_start_date',
        ),
    ]
