# Generated by Django 5.2.2 on 2025-06-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_rename_membership_start_end_membership_membership_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='last_payment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='gym_location',
            field=models.CharField(choices=[('Hounslow', 'Hounslow')]),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Regular', 'Regular')]),
        ),
    ]
