# Generated by Django 5.2.2 on 2025-06-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_membership_last_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='post_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
