# Generated by Django 5.2.2 on 2025-06-29 15:28

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_alter_membership_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='country',
            field=django_countries.fields.CountryField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membership',
            name='post_code',
            field=models.CharField(default='asdfa', max_length=20),
            preserve_default=False,
        ),
    ]
