# Generated by Django 5.2.2 on 2025-06-09 17:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_title', models.CharField(unique=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('difficulty', models.CharField()),
                ('intensity', models.CharField()),
                ('instruction', models.TextField()),
                ('equipment', models.CharField()),
                ('targeted_muscles', models.CharField()),
                ('indirectly_targeted_muscles', models.CharField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
