# Generated by Django 5.2.2 on 2025-06-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='recommended_reps',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='recommended_sets',
            field=models.CharField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='indirectly_targeted_muscles',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instruction',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='intensity',
            field=models.CharField(choices=[('light', 'Light'), ('moderate', 'Moderate'), ('intense', 'Intense')]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='targeted_muscles',
            field=models.CharField(max_length=300),
        ),
    ]
