# Generated by Django 5.2.2 on 2025-06-21 11:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_exercise_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavouriteExercises',
            new_name='FavouriteExercise',
        ),
    ]
