# Generated by Django 5.2.2 on 2025-06-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_rename_favouriteexercises_favouriteexercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouriteexercise',
            old_name='exercise_id',
            new_name='exercise',
        ),
    ]
