# Generated by Django 5.2.2 on 2025-06-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_rename_exercise_id_favouriteexercise_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='recommended_sets',
            field=models.IntegerField(),
        ),
    ]
