# Generated by Django 5.2.2 on 2025-06-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_alter_exercise_recommended_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='recommended_reps',
            field=models.IntegerField(),
        ),
    ]
